# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "news.baml": "enum Sentiment {\n  POSITIVE\n  NEGATIVE\n  NEUTRAL\n}\n\nenum NewsCategory {\n  WORLD\n  SPORTS\n  BUSINESS\n  SCIENCE_TECHNOLOGY\n  POLITICS\n  ENTERTAINMENT\n  HEALTH\n  OTHER\n}\n\nclass Entity {\n  name string @description(\"The entity name as it appears in the text\")\n  entity_type string @description(\"One of: PERSON, ORGANIZATION, LOCATION, PRODUCT, EVENT\")\n  relevance_score float @description(\"0.0 to 1.0 - how central this entity is to the article\")\n}\n\nclass ArticleAnalysis {\n  headline_rewrite string @description(\"A cleaner, more neutral version of the headline\")\n  category NewsCategory\n  sentiment Sentiment\n  sentiment_confidence float @description(\"0.0 to 1.0\")\n  entities Entity[] @description(\"Up to 5 key named entities\")\n  key_claims string[] @description(\"2-4 factual claims made in the article\")\n  summary string @description(\"One sentence summary, max 30 words\")\n  bias_flags string[] @description(\"Any loaded/biased language detected; empty list if none\")\n}\n\nclass Article {\n  headline string\n  body string\n}\n\nfunction AnalyzeArticle(headline: string, body: string) -> ArticleAnalysis {\n  client GroqClient\n  prompt #\"\n    You are a professional news analyst. Analyze the following article with precision.\n    HEADLINE: {{ headline }}\n    BODY: {{ body }}\n    {{ ctx.output_format }}\n  \"#\n}\n\nclient<llm> GroqClient {\n  provider openai\n  options {\n    base_url \"https://api.groq.com/openai/v1\"\n    api_key env.GROQ_API_KEY\n    model \"llama-3.1-8b-instant\"\n    temperature 0\n  }\n}\n",
}

def get_baml_files():
    return _file_map