# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class Article(BaseModel):
    headline: typing.Optional[str] = None
    body: typing.Optional[str] = None

class ArticleAnalysis(BaseModel):
    headline_rewrite: typing.Optional[str] = Field(default=None, description='A cleaner, more neutral version of the headline')
    category: typing.Optional[types.NewsCategory] = None
    sentiment: typing.Optional[types.Sentiment] = None
    sentiment_confidence: typing.Optional[float] = Field(default=None, description='0.0 to 1.0')
    entities: typing.List["Entity"] = Field(description='Up to 5 key named entities')
    key_claims: typing.List[str] = Field(description='2-4 factual claims made in the article')
    summary: typing.Optional[str] = Field(default=None, description='One sentence summary, max 30 words')
    bias_flags: typing.List[str] = Field(description='Any loaded/biased language detected; empty list if none')

class Entity(BaseModel):
    name: typing.Optional[str] = Field(default=None, description='The entity name as it appears in the text')
    entity_type: typing.Optional[str] = Field(default=None, description='One of: PERSON, ORGANIZATION, LOCATION, PRODUCT, EVENT')
    relevance_score: typing.Optional[float] = Field(default=None, description='0.0 to 1.0 - how central this entity is to the article')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
