# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Article": types.Article,
    "stream_types.Article": stream_types.Article,

    "types.ArticleAnalysis": types.ArticleAnalysis,
    "stream_types.ArticleAnalysis": stream_types.ArticleAnalysis,

    "types.Entity": types.Entity,
    "stream_types.Entity": stream_types.Entity,


    "types.NewsCategory": types.NewsCategory,

    "types.Sentiment": types.Sentiment,

}