# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class NewsCategory(str, Enum):
    WORLD = "WORLD"
    SPORTS = "SPORTS"
    BUSINESS = "BUSINESS"
    SCIENCE_TECHNOLOGY = "SCIENCE_TECHNOLOGY"
    POLITICS = "POLITICS"
    ENTERTAINMENT = "ENTERTAINMENT"
    HEALTH = "HEALTH"
    OTHER = "OTHER"

class Sentiment(str, Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"

# #########################################################################
# Generated classes (3)
# #########################################################################

class Article(BaseModel):
    headline: str
    body: str

class ArticleAnalysis(BaseModel):
    headline_rewrite: str = Field(description='A cleaner, more neutral version of the headline')
    category: NewsCategory
    sentiment: Sentiment
    sentiment_confidence: float = Field(description='0.0 to 1.0')
    entities: typing.List["Entity"] = Field(description='Up to 5 key named entities')
    key_claims: typing.List[str] = Field(description='2-4 factual claims made in the article')
    summary: str = Field(description='One sentence summary, max 30 words')
    bias_flags: typing.List[str] = Field(description='Any loaded/biased language detected; empty list if none')

class Entity(BaseModel):
    name: str = Field(description='The entity name as it appears in the text')
    entity_type: str = Field(description='One of: PERSON, ORGANIZATION, LOCATION, PRODUCT, EVENT')
    relevance_score: float = Field(description='0.0 to 1.0 - how central this entity is to the article')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
